### ISSUE TITLE
env.yml incompatibility: ‘HTMLExporter’ object has no attribute ‘template_path’

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/nixtlats#10]
It seems that fastai has some dependency problems from the nbconvert library from jupyter
downgrading nbconvert solved the issue, seems to me yaml environment needs version protections.
https://forums.fast.ai/t/htmlexporter-object-has-no-attribute-template-path/80775/15

downgrading the nbconvert library solved the issue
conda install nbconvert=5.6.1

**Comment by FedericoGarza** [comment]
I'm closing this issue as the problem has not arisen.
