### ISSUE TITLE
Datasets: evaluation benchmark example within the dataset

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/nixtlats#19]
I think it would be extremely handy to have a simple evaluation example for the dataset tasks within the notebook.
Where we import the respective metric and try a simple benchmark, the measurement could be the one at the bottom of the evaluation table in each dataset.

Open AI gym library has a tiny wiki for each RL where they explicitly state what is to "solve" a task.
Example https://github.com/openai/gym/wiki/BipedalWalker-v2.

**Comment by FedericoGarza** [comment]
Solved for `M4` through the class [`M4Evaluation`](https://github.com/Nixtla/nixtlats/blob/master/nixtlats/data/datasets/m4.py#L173). I think it would be better to have a separate issue for each dataset.
